### ISSUE TITLE
Disabling while offline in winter mode

### ISSUE THREAD

**Issue by greentux** [geertmeersman/robonect#109]
Hi,

while the mower is in winter mode (service, cellar, etc) the log has a lot of error messages not reaching the mower. 
Ist it possible to have a "disable" possibility or do I have to disable the full integration?

thx

**Comment by geertmeersman** [comment]
Hi Matthias, I am planning on "keeping" the sensor data in a data store, meaning that it will always show the last known state. This should solve this for you. It's linked to #88 
I plan to have this before end of december (during my holidays) :-)

**Comment by geertmeersman** [comment]
Hi, can you try this one out : https://github.com/geertmeersman/robonect/releases/tag/v2.5.1-beta.9

But you will need to power the mower on when you have installed it, so it can fetch all data.
There is also a new option that you now can configure (winter mode)

**Comment by greentux** [comment]
works fine for me!
