### ISSUE TITLE
TEMP_CELSIUS used by robonect is a deprecated constant

### ISSUE THREAD

**Issue by Fossy777** [geertmeersman/robonect#121]
**Describe the bug**
I get the following message in my HomeAssistant instance running robonect saying "TEMP_CELSIUS was used from robonect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead"

**To Reproduce**
Install robonect on actual release of HomeAssistant or update an existing instance of HomeAssistant that has this integration installed

**Expected behavior**
Use UnitOfTemperature.CELSIUS instead to keep robonect compatible to future versions of HomeAssistant

**Comment by geertmeersman** [comment]
Thanks! Haven't upgraded yet myself, but will fix it

**Comment by geertmeersman** [comment]
Should be fixed with https://github.com/geertmeersman/robonect/releases/tag/v1.5.4

Can you confirm?

**Comment by udochrist** [comment]
Hi,
I don't want to hijack this issue and can open a separate one, but for me there is one more constant that is marked deprecated. Maybe you want to fix this in one go: HA version is 2024.01

**ELECTRIC_POTENTIAL_VOLT** was used from robonect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please create a bug report at https://github.com/geertmeersman/robonect/issues
TEMP_CELSIUS was used from robonect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/geertmeersman/robonect/issues

**Comment by geertmeersman** [comment]
Hi @udochrist , this was also changed in v1.5.4: https://github.com/geertmeersman/robonect/commit/5d8e9193ea6f1ab59acd46cfe7cc263c8c03b781

**Comment by udochrist** [comment]
Thx. I‘ll give it a try later today then.

**Comment by geertmeersman** [comment]
Thanks and let me know if it was fixed, but I'm quite confident :-)

**Comment by udochrist** [comment]
Working. The two deprecations are no longer logged-

**Comment by Fossy777** [comment]
jep - working, confirmed! :-)
