### ISSUE TITLE
Duplicate battery sensor

### ISSUE THREAD

**Issue by Pulpyyyy** [geertmeersman/robonect#127]
Hello

Seems there are some duplicates in sensor ?
![image](https://github.com/geertmeersman/robonect/assets/32004297/8c481c06-e12c-429e-a762-8d4a82bf269b)

Regards

**Comment by geertmeersman** [comment]
Hi, this is because 1 is coming from MQTT and 1 coming from the REST sensor.
The MQTT sensor is create "automatically" and the rest sensor is created with quite some attributes.
So it is "wanted" behaviour, but if you don't need the extra sensor, you can alway disable it in HA
