### ISSUE TITLE
No "Reset error" button 

### ISSUE THREAD

**Issue by me2000** [geertmeersman/robonect#151]
I do not see a button to "reset error" for my mower as mentioned and shown in this issue: https://github.com/geertmeersman/robonect/issues/28

I have activated the integration and other buttons (EOD, Start, Stop) and sensors(battery soc ...) are working as expected But I do not see the button to reset an error.

When looking in Settings->Integrations->Robonect I see 8 buttons (Auto, EOD, 2xMower, Manuell, Start, Stop, Home), I would expect a button here "Error reset)

HA is at 2024.4.4, HACS at 1.34.0 and Robonect at 1.6.2. The integration is linked to the mower through MQTT.

Is that a user error on my side? Is that a bug? Or works as designed?

**Comment by geertmeersman** [comment]
The reason why you don't see the button is because on the MQTT payload there is no "known to me" topic on which we can reset the error.
So it's only available when you enable the REST functionality

**Comment by me2000** [comment]
Wow, that was a quick answer, thank you! I will then create my own button and call the web api to clear errors. Hopefully with a new firmware (soon.tm) this feature will be added.

**Comment by geertmeersman** [comment]
If you know the MQTT command I will be more than happy to add it :-)

**Comment by me2000** [comment]
> If you know the MQTT command I will be more than happy to add it :-)

Would love to, but apparently there is none. In the German forum one can find multiple feature requests for this and a post from July 2023 thta confirms that this is not possible as of then. As there was no new firmware released since then I would expect this statement to be still true. (https://forum.robonect.de/viewtopic.php?p=31807&hilit=mqtt+fehler+zur%C3%BCcksetzen#p31807)

**Comment by me2000** [comment]
> Btw any reason why you don't use MQTT combined with REST? If you just activate the REST on the integration you will be have the button

I wanted to avoid this as I would like to keep it clean and simple. TBH I overlooked that MQTT is prioritized over REST so this might very well be the way to go.
