### ISSUE TITLE
Exception 0 warnings

### ISSUE THREAD

**Issue by Th3M1k3y** [geertmeersman/robonect#152]
**Describe the bug**
Getting a lot of Exception 0 warnings in log.

**To Reproduce**

1. Go to 'Logs' > Home Assistant Core

**Expected behavior**
Everything seems to work fine, expected no warnings.

**Screenshots**
![image](https://github.com/geertmeersman/robonect/assets/29869794/8f95ebb7-30dc-4821-be44-65cd5c4d0ae1)

**Comment by geertmeersman** [comment]
If you make the request yourself, what does it respond?

**Comment by Th3M1k3y** [comment]
It responds with the status.

`{"name": "Dot", "id": "xxxxxxxxxxxxx", "status": {"status": 17, "distance": 0, "stopped": true, "duration": 51062, "mode": 2, "battery": 99, "hours": 2190}, "timer": {"status": 2}, "blades": {"quality": 85, "hours": 0, "days": 14}, "wlan": {"signal": -68}, "health": {"temperature": 34, "humidity": 11}, "clock": {"date": "2024-05-02", "time": "09:49:13", "unix": 1714643353}, "successful": true}`
