### ISSUE TITLE
Status entity general error

### ISSUE THREAD

**Issue by mksbmw** [geertmeersman/robonect#157]
Integration robonect with Gardena Sileno City. All entities ok up to Status "General error".

Support does not identify the problem from robonect

![Screenshot_20240520_161730_Home Assistant](https://github.com/geertmeersman/robonect/assets/99194009/38caba05-7fc9-47d3-91aa-a9ac0a50abdd)
![Screenshot_20240519_192147_Chrome](https://github.com/geertmeersman/robonect/assets/99194009/9867ab76-e767-4ab5-be5a-640cd4c532fe)

**Comment by geertmeersman** [comment]
Hi, could you enable the debug and provide the logs?
And feel free to join on discord to exchange easily

**Comment by mksbmw** [comment]
Hello, first I would like to thank you for taking care of the problems of people like me.... attached is the log file. Unfortunately, I'm not a programmer, but I hope I can still follow you somewhat ;) mfg Markus
[home-assistant_robonect_2024-05-21T08-58-52.827Z.log](https://github.com/geertmeersman/robonect/files/15387359/home-assistant_robonect_2024-05-21T08-58-52.827Z.log)

**Comment by geertmeersman** [comment]
Hi Markus, any update?

**Comment by mksbmw** [comment]
Hi,
Thanks for asking, I deleted the robonect integration completely and added it again, but the "status" message is still incorrect. After the new setup, all other entities were found and I can control everything and receive data from the motor or battery etc. Only the entity "status" (mowing, parking, charging) is incorrect. In the robonect app, mqtt is shown as "connected" and there I can see the "status" (mowing, parking, charging).

**Comment by geertmeersman** [comment]
Can you activate debug logging, reload the integration, and then stop debug?
And then send me the txt file? 
Will have a look at it

**Comment by mksbmw** [comment]
[error_log-2.txt](https://github.com/geertmeersman/robonect/files/15435107/error_log-2.txt)
Thanks very much

**Comment by geertmeersman** [comment]
The integration is taking the status from MQTT: 2024-05-24 15:34:09.124 DEBUG (MainThread) [custom_components.robonect.sensor] [sensor|async_setup_entry|skipping since MQTT] mower/status

so it should be identical to what your mower pushes to your broker... I can add extra debug logging if you want

**Comment by mksbmw** [comment]
The status is there in the list, but it doesn't tell you whether the mower is parked, driving or charging. It just shows "Error".
It should be like this 
![image](https://github.com/geertmeersman/robonect/assets/99194009/0a310c51-48e6-47f9-806e-bd302ff5de0c)
And is like this 
![image](https://github.com/geertmeersman/robonect/assets/99194009/f5bbd676-5007-4732-afd5-591f0f8e3493)

**Comment by geertmeersman** [comment]
You first screenshot shows indeed the status, the 2nd one shows the last error code...

**Comment by mksbmw** [comment]
Yes the first screenshot is not from my home assistant. Was only to showVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Geert Meersman ***@***.***> Datum: 24.05.24  17:25  (GMT+01:00) An: geertmeersman/robonect ***@***.***> Cc: mksbmw ***@***.***>, Author ***@***.***> Betreff: Re: [geertmeersman/robonect] Status entity general error (Issue #157) 
You first screenshot shows indeed the status, the 2nd one shows the last error code...

**Comment by mksbmw** [comment]
First Screenshot was not from my home assistant, was only to Show you.
It's not that bad, I just don't see the status, I don't want to take up your time so often. I'm glad that the mower was able to be integrated at all...:)

**Comment by geertmeersman** [comment]
I think that the reason you don't see the status is that it hasn't changed. The moment the broker received the new status it will push it to HA

**Comment by mksbmw** [comment]
Status works now, I wrote the name of the topic differently in mqtt than in the robonect app, so mqtt didn't transfer anything at all. Thank you again for your help

**Comment by geertmeersman** [comment]
Perfect! Thanks for the feedback 👍
