### ISSUE TITLE
Use mqtt as alternative to polling for faster response

### ISSUE THREAD

**Issue by SciLor** [geertmeersman/robonect#18]
Hey,
it would be useful to integrate the mqtt communication as alternative for the web api polling.
This will update the data much faster and only when needed as mqtt pushes the data.

**Comment by geertmeersman** [comment]
Hi, it is already done in the development stream.

So new version will come soon 👍

See here:
https://community.home-assistant.io/t/robonect-module-in-husqavarna-automower-via-mqtt-vacuum/58180/90?u=geertmeersman

Op vr 19 mei 2023 15:42 schreef 0xbadbee ***@***.***>:
