### ISSUE TITLE
 Error message during integration, Error doing job: Future exception was never retrieved (None)

### ISSUE THREAD

**Issue by Rockhound53** [geertmeersman/robonect#184]
Logger: homeassistant
Quelle: helpers/frame.py:197
Erstmals aufgetreten: 19:13:41 (1 Vorkommnisse)
Zuletzt protokolliert: 19:13:41

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robonect/sensor.py", line 369, in update_busevent
    self.update_ha_state()
  File "/config/custom_components/robonect/entity.py", line 127, in update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in async_write_ha_state
    report_non_thread_safe_operation("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'robonect' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/robonect/entity.py, line 127: self.async_write_ha_state(). Please report it to the author of the 'robonect' custom integration.

I get the above error message in the current Home Assistant application. 

Can someone tell me what could be causing this?

Thanks and Greetings

**Comment by geertmeersman** [comment]
Hi, I'll check it out asap.
In 2 weeks I have some holidays so will have some extra debug time 💪💪

It's currently only a warning, you are not doing anything wrong, it's just how some calls are done. Will fix it

**Comment by geertmeersman** [comment]
Should be ok now, thanks for opening the issue

**Comment by Rockhound53** [comment]
Hallo, sie kommen doch aus Deutschland, oder?

Wäre es möglich, einen Button einzurichten, um die Messer zurückzusetzen?

Das ist so das einzige, weswegen ich noch in die Weboberfläche von robonect
muss, den Rest mache ich aus HomeAssistant.

Besten Dank vorab, auch für die Problemlösung! Super Arbeit!

Viele Grüße

Geert Meersman ***@***.***> schrieb am Fr., 26. Juli 2024,
10:18:

**Comment by geertmeersman** [comment]
I'm living in Belgium, so no but for sure I understand German.
I will check it out, but to my memory I haven't seen the api call to reset the blades.

**Comment by geertmeersman** [comment]
@Rockhound53 , found how to do it, will include it in the next release

**Comment by Rockhound53** [comment]
Awesome, thank you so much!

Geert Meersman ***@***.***> schrieb am Fr., 26. Juli 2024,
12:30:

**Comment by geertmeersman** [comment]
@Rockhound53 , available in [Release v1.8.0](https://github.com/geertmeersman/robonect/releases/tag/v1.8.0)

**Comment by Rockhound53** [comment]
Work Like a Charm! Thanks!

Geert Meersman ***@***.***> schrieb am Fr., 26. Juli 2024,
17:59:

**Comment by Rockhound53** [comment]
Hi,

Sometimes i get the Info below:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.robonect
Quelle: custom_components/robonect/__init__.py:246
Integration: Robonect (Dokumentation, Probleme)
Erstmals aufgetreten: 20:38:13 (1 Vorkommnisse)
Zuletzt protokolliert: 20:38:13

Exception

Any suggestions why?

Thanks

Geert Meersman ***@***.***> schrieb am Fr., 26. Juli 2024,
17:59:

**Comment by geertmeersman** [comment]
If it is frequent you could try to activate debug mode

**Comment by Rockhound53** [comment]
Hi,

i aktivate the debug Mode, but where can i find the Log?

Thanks & Regards

Am So., 28. Juli 2024 um 21:18 Uhr schrieb Geert Meersman <
***@***.***>:

**Comment by geertmeersman** [comment]
If you stop the debug, it will download the log to your pc.
I have described it in the readme

**Comment by Rockhound53** [comment]
Hi,

here are the Log, hope it helps.

Greetings

Am Mo., 5. Aug. 2024 um 15:11 Uhr schrieb Geert Meersman <
***@***.***>:
