### ISSUE TITLE
ON/OFF switches for OUT 1 & OUT 2

### ISSUE THREAD

**Issue by stosoorok** [geertmeersman/robonect#195]
New idea, maybe add a ON/OFF switch for out1 and out2?

http://172.16.xxx.xxx/ext2?gpioout=16&gpiomode=0&save=
http://172.16.xxx.xxx/ext2?gpioout=16&gpiomode=1&save=

**Comment by geertmeersman** [comment]
Work in progress
![image](https://github.com/user-attachments/assets/bca0da2d-74fb-4ae5-9e46-e72b8d86313b)

**Comment by geertmeersman** [comment]
Ongoing...
![image](https://github.com/user-attachments/assets/fda0297e-44d2-4fe8-94f4-7b9ca1d69d0b)

**Comment by geertmeersman** [comment]
Should be implemented in release v2.0.0

**Comment by geertmeersman** [comment]
If all is fine, please close the issue 🙏
