### ISSUE TITLE
Send 'Joystick'-commands to robonnect

### ISSUE THREAD

**Issue by MarcV16** [geertmeersman/robonect#197]
Is it possible to create actions (like you did for a job) to give the mower commands to do.
These are the action that you do in 'Joystick-mode'

Something like: 3 seconds forward, turn 45 deg right,.....

I saw something in the robonect-forum to perform 6sec forwards , 20% of speed,  
`http://IP-vom-Mäher/xml?cmd=direct&left=20&right=20&timeout=6000`

To turn, you give one wheel the command to drive backward (-20) and the other forwards (20)

But it would be nice to create the actions direct from the HA-addon.

Thank you

**Comment by geertmeersman** [comment]
Should be solved  with the release 1.9.0
