### ISSUE TITLE
The Lovelace example uses vacuum entity, which does not exist after 2.0.0

### ISSUE THREAD

**Issue by naschine** [geertmeersman/robonect#211]
Hi there!

Thank you for your ongoing support of the Robonect integration.

I'm using your example card pretty much 1:1, but since release 2.0.0 the vacuum entity which was used before is now non existent.

It probably isn't a direct replacement after looking at both entities in the developer tools, same for the commands according to the documentation.

If the example card could be updated to 2.0.0 standards as well, this would be awesome!

Thank you very much in advance!

**Comment by geertmeersman** [comment]
I changed it but forgot to merge it from the dev branch 👍 
Thanks for noticing
