### ISSUE TITLE
error: exception

### ISSUE THREAD

**Issue by Rockhound53** [geertmeersman/robonect#214]
Since the last update, many have been getting the following error messages:

This error was caused by a custom integration

Logger: custom_components.robonect
Source: custom_components/robonect/__init__.py:312
Integration: Robonect (documentation, problems)
First Occurred: 13:48:09 (44 occurrences)
Last logged: 15:17:44

Exception

I've had this error in the past, but not with this frequency.

any ideas to fix this?

thanks

**Comment by Rockhound53** [comment]
here it is:

[home-assistant_robonect_2024-10-09T13-38-28.501Z.log](https://github.com/user-attachments/files/17309161/home-assistant_robonect_2024-10-09T13-38-28.501Z.log)

**Comment by geertmeersman** [comment]
Can you try this one: https://github.com/geertmeersman/robonect/releases/tag/v2.0.2-beta.2

**Comment by Rockhound53** [comment]
Hi, 

I just looked again in the web interface and saw that I still had MQTT active, but that I had no longer installed it the last time I reinstalled HA and had also removed the entities. 

After switching off MQTT in the WebInterface, the error no longer occurred. I would keep an eye on it for a while. 

If it happens again, I would try the fix!

Thanks for the quick response.

**Comment by geertmeersman** [comment]
I think the error is/was related to the switching of the rest  client to the internal HA  httpx one, since they made some changes.
They don't define a timeout, which created the exceptions. So this is normally fixed now with the 2.0.2 release
