### ISSUE TITLE
Mower keeps waking up and getting back to sleep

### ISSUE THREAD

**Issue by pdecat** [geertmeersman/robonect#218]
**Describe the bug**

Hi, my Husqvarna Automower 315X keeps waking up, emits two beeps, I see updates of GPS coordinates in HA, and then gets back to sleep. I've got the impression this behavior change is very recent, as I can hear the beeps from my office.

Any recent changes that could explain this?

PS: thank you so much for this integration, it's awesome!

**To Reproduce**

N/A

**Expected behavior**

Mower should not wake-up all the time.

**Screenshots**

![image](https://github.com/user-attachments/assets/537a7d27-477e-42ae-8130-9474006d0db0)

**Log information**

N/A (I believe)

**Additional context**

Integration version: v2.0.3
Update interval: 2 minutes
Both MQTT and REST API are enabled since I started to use this integration several months ago.

**Comment by geertmeersman** [comment]
Ah perhaps the GPS JSON command wakes him up, will remove it and you can test it

**Comment by geertmeersman** [comment]
Can you try if 2.0.4 solves it

**Comment by pdecat** [comment]
Testing in progress...

**Comment by pdecat** [comment]
That apparently fixed the issue, thank you so much! :rocket:

**Comment by geertmeersman** [comment]
With pleasure 🥳

**Comment by pdecat** [comment]
Maybe I spoke too soon, it did wake up after 8 minutes:

![image](https://github.com/user-attachments/assets/ae6cc727-278a-48bb-a54f-a253b78c260f)

**Comment by pdecat** [comment]
Will keep an eye (and ear) on it :)

**Comment by geertmeersman** [comment]
Any news?

**Comment by pdecat** [comment]
Everything seems fine, I don't ear beeps anymore.
