### ISSUE TITLE
Winter mode

### ISSUE THREAD

**Issue by zeekens** [geertmeersman/robonect#224]
**Is your feature request related to a problem? Please describe.**
Winter/off-season mode/switch

**Describe the solution you'd like**
It would be great if there was a toggle for the integration per robot where you could disable/enable connection attempts. Now when I've tucked Mow in for the winter I get error messages an it would be cool not to have to disable the whole integration

**Comment by geertmeersman** [comment]
Good suggestion, will look into it

**Comment by zeekens** [comment]
Well would you look at that, fastest gun in the west :)

**Comment by zeekens** [comment]
Done and done
