### ISSUE TITLE
mower_mode?

### ISSUE THREAD

**Issue by MarcFinns** [geertmeersman/robonect#230]
**Describe the bug**
I installed and configured the integration, and I can correctly see the sensors.
I tried to use the example card, that references a sensor.automower_mower_mode.
I do not see where this is defined

**To Reproduce**
Install the integration and the provided lovelace card

**Expected behavior**

ButtonCardJSTemplateError: TypeError: Cannot read properties of undefined (reading 'state') in 'if (states['sensor.automower_mower_mode'].state == '0' ) return 'var(--

**Screenshots**

**Log information**
If possible activate debug logging on the component as mentioned below.

<https://www.home-assistant.io/integrations/logger/>

```yaml
logger:
  default: warning
  logs:
    custom_components.robonect: debug
```

**Additional context**

**Comment by geertmeersman** [comment]
Hi Marc, could you join on Discord? Link to the server in the readme.
It would be interesting to get a complete list of your entities

**Comment by MarcFinns** [comment]
> Hi Marc, could you join on Discord? Link to the server in the readme.
> 
> It would be interesting to get a complete list of your entities

Hi Geert, thanks for your kind reply. I believe i somewhat managed. As a suggestion: Perhaps it would be useful for the uninitiated to add a short description on the mqtt side of the configuration, and how many entities one should expect. HA learning curve remains steep... thx again!

**Comment by geertmeersman** [comment]
It can take indeed a little while before the mqtt entities show up.
Good luck and if there's anything, just ask

**Comment by MarcFinns** [comment]
Thanks. It's going to be in spring time I guess... removing the mower today!
