### ISSUE TITLE
Clear Error/StopDer 

### ISSUE THREAD

**Issue by webflash-aj** [geertmeersman/robonect#28]
**Is your feature request related to a problem? Please describe.**
For example, the robot is lifted by our children, or it gets caught in a narrow traverse, or it had something else and was manually placed in a new location.

**Describe the solution you'd like**
The error can be reset via the Robonect GUI.
But for the start button there is (as far as I know) no API via MQTT.
A service in HA would be great for this.

**Describe alternatives you've considered**
none

**Additional context**
Thank you very much for the HA integration of Robonect. I was just about to try my hand at implementing a mowing job as a service today via REST. But unfortunately failed to do so.
With your HA integration it was a short and painless thing.

The "Lovelance example" only works with "custom cards". It would be nice if the Requierements were listed.
And/or maybe one or two more examples would be available

**Comment by geertmeersman** [comment]
Hi,

I have added the custom  card requirements.
More examples is not really the goal of my integration, since it is a backend integration, but if people  push me other examples I will add them to the README.

Since I have the start button in the integration, I suppose this  solves your issue?
Can I close it? Or is there still an outstanding question/request?

**Comment by webflash-aj** [comment]
Hi

If I ever have a nice dashboard together, I will be happy to share it. Currently it is still too messy.

Unfortunately, the "Start" button does not work in case of error. I would need a "reset error" button. See screenshot.

Andy

![image](https://github.com/geertmeersman/robonect/assets/73847757/6c9b68c1-a9d8-4c2f-a6b4-f0bf2f064d34)

**Comment by geertmeersman** [comment]
Ok! got it. I think I can have that fixed

**Comment by geertmeersman** [comment]
Let me know if it is ok, then I close the issue 👍

**Comment by geertmeersman** [comment]
That's indeed not normal! Going to see what's going on.  I suppose you have the units enabled in MQTT?

**Comment by webflash-aj** [comment]
No, they were not enabled. Just enabled them and rebooted robonect.

Now i will get the following error:
![image](https://github.com/geertmeersman/robonect/assets/73847757/058aec14-c081-429f-8c22-c20a0f81e6c8)
