### ISSUE TITLE
Option to change timers without entering the whole config (enable/disable)

### ISSUE THREAD

**Issue by BoneheadFraggle** [geertmeersman/robonect#69]
**Is your feature request related to a problem? Please describe.**
I propose switches/input_booleans for enabling/disabling timers

**Describe the solution you'd like**
Something matching "curl -XPOST -v --user <user>:<pw> 'http://<host>/json?cmd=timer&timer1&enable=0'"

**Describe alternatives you've considered**
I can do it manually, but I think more users than me would like the option to easily toggle timers without needing to configuring manual tasks

**Additional context**
Switches are perfect for use with automations for example.

**Comment by geertmeersman** [comment]
Thx, will implement it somewhere next week
