### ISSUE TITLE
Robonect V1.1.0 only 35 entity; vacuum missing

### ISSUE THREAD

**Issue by jove01** [geertmeersman/robonect#73]
**Describe the bug**
Today I installed this HACS-Integration for Gardena R40Li (2015) and the actual Robonect-Firmware V1.3b. I followed this guide/video:

[meine-digitale-welt.de/robonect-integration](url)

After restart the Integration has only 35 entity. 

I tried different things: I deleted the Integration and the the HACS-Download. I restarted the system, not only HA. Then I folowed all the steps, nothing changed to before.

**To Reproduce**

**Expected behavior**

All entity - specially Vacuum - are generated.

**Screenshots**

**Robonect**

<img width="241" alt="image" src="https://github.com/geertmeersman/robonect/assets/116289742/f76f0856-2835-4298-9f6e-b075de0b7798">

**MQTT-Explorer**

<img width="250" alt="image" src="https://github.com/geertmeersman/robonect/assets/116289742/501e228c-7f26-42c0-b3f4-f677513f2bc4">

**HA-Integration**

<img width="420" alt="image" src="https://github.com/geertmeersman/robonect/assets/116289742/5d443fcf-5d65-476c-83e2-be6fd03508ca">

**Entity vacuum**

<img width="760" alt="image" src="https://github.com/geertmeersman/robonect/assets/116289742/de4db4dd-e12d-4b78-8ce9-37c30be3e5ea">

**Log information**
If possible activate debug logging on the component as mentioned below.

https://www.home-assistant.io/integrations/logger/

```
logger:
  default: warning
  logs:
    custom_components.nexxtmove: debug
```

**Additional context**

**System**

<img width="353" alt="image" src="https://github.com/geertmeersman/robonect/assets/116289742/6de42f1e-4558-44c0-9b05-094110c84ba9">

<img width="219" alt="image" src="https://github.com/geertmeersman/robonect/assets/116289742/062d7ccd-87bb-4c5b-aed2-f9ff25bb8be7">

Please let me know what additional information you need.

Thank you

**Comment by geertmeersman** [comment]
Hi, normally the MQTT sensors are added when a new topic is published on the broker.
Could you provide me with the home-assistant log? or activate the debugging as described in the readme?
Thx

**Comment by geertmeersman** [comment]
Problems always have a solution ;-)
Will let you know

**Comment by geertmeersman** [comment]
MQTT Subscribing to automower/#

Can you confirm your robonect MQTT topic is "automower" ? :-) I think this is why it doesn't add any mqtt sensor... your configured topic will be named differently ;-)

**Comment by jove01** [comment]
Yes I think so
automover

![grafik](https://github.com/geertmeersman/robonect/assets/116289742/4d42d273-0ebc-41ad-a43d-a84e7c9137b2)

And in MQTT-Explorer also

![grafik](https://github.com/geertmeersman/robonect/assets/116289742/3f055e1a-91e6-4187-bcbb-a393bd5052bd)


**Are there enough messages?**

And I think, there is no change from o to 0.

In my firtst try, I have changed the name in HA (maybe in Robonect). Then I deleted all, maked many restrarts and installed new.

Thanks

**Comment by geertmeersman** [comment]
automower != automover :-)

**Comment by geertmeersman** [comment]
I mean, when you have set up my integration, you have let the mqtt topic to the standard automower one, and your topic is called automover.
So you need to either change it in robonect, or in the HA setup...

**Comment by jove01** [comment]
I am so blind!!! 121 entity

Thank you very much for your help.
