### ISSUE TITLE
New entity type lawnmower

### ISSUE THREAD

**Issue by Se7enair** [geertmeersman/robonect#81]
**Is your feature request related to a problem? Please describe.**
In Homeassistanr 2023.9 there will be a new entity type called [lawnmower](https://rc.home-assistant.io/integrations/lawn_mower).

**Describe the solution you'd like**
Change of entity type from vacuum cleaner to lawn mower.

**Describe alternatives you've considered**
If homeassstant gives us this opportunity, we should grab it.

**Additional context**
Nice work so far. Love it!

**Comment by geertmeersman** [comment]
Hi Christophe,

it's sitting in my dev environment, waiting for the release :-)
![image](https://github.com/geertmeersman/robonect/assets/1844091/f7c096fe-a2a3-4079-ba42-e0693d9c36b3)
![image](https://github.com/geertmeersman/robonect/assets/1844091/dc86ca15-8dd7-41f5-be5c-ec7bcaff2956)

**Comment by Se7enair** [comment]
Wonderful 😍
So you will release a update as soon Homeassistant 2023.9 is finally released? Will be soon enough to test it in this lawn season 😎☀🌿

**Comment by Se7enair** [comment]
> Yes, and for the moment I will also keep the vacuum, giving people the opportunity to migrate whatever they have built as automations, frontend, etc...

So I think this can be closed? Or do you want to wait till the release?
