### ISSUE TITLE
Restore entities at restart when mower is unavailable?

### ISSUE THREAD

**Issue by BoneheadFraggle** [geertmeersman/robonect#88]
If the mower is out of WiFi range when HA restarts, the integration fails to load.
I can reload the integration as soon as the mower is connected again, and then everything works. 
But that is a manual task I would like to avoid. And in the meantime before I can reload it, all the nice gauges are broken in the dashboard.

**Describe the solution you'd like**
If possible, it would be nice to have the integration load up with restored values until it can connect to the mower.
Maybe even a state that shows Active/Restored or similar?

**Describe alternatives you've considered**
Leave as today. It's a minor issue. Just occurs if you have i bit of bad timing when you restart HA.

**Additional context**

**Comment by geertmeersman** [comment]
Not to be set to stale

**Comment by geertmeersman** [comment]
No need to stale it... It's for the holidays 😀

**Comment by BoneheadFraggle** [comment]
> Hi, can you give the beta release a try?
> 
> https://github.com/geertmeersman/robonect/releases/tag/v1.6.1-beta.7

I'd love to help.
I just upgraded and rebooted, and it behaved a bit strange even though I put the mower online first.
Lots of unavailable (removed/restored) sensors, and it doesn't come alive at all.
I'll start with removing everything that seems dead and restart + reload.

Maybe I should start over with a clean config to get better testing conditions?

Just tell me if you want me to try out specific things.

**Comment by geertmeersman** [comment]
Could you join on Discord? https://discord.gg/wZHsA4aGvS
Easier to exchange.
You can already enable debug to see what's happening
