### ISSUE TITLE
Extra info missing for mower

### ISSUE THREAD

**Issue by Pulpyyyy** [geertmeersman/robonect#90]
Hello,

Thanks for creating this integration ! I will replace data i retreive from MQTT.
By the way, I still missing some details :
![image](https://github.com/geertmeersman/robonect/assets/32004297/fc3949e5-b1ff-439d-bf18-6a1fbadcdab3)
 May you add then in future release ?

**Comment by geertmeersman** [comment]
Hi, there sensors should be there. They are auto detected and correctly visible in my setup.

Can you list the sensors in the integration page?
Btw feel free to join the discord channel

**Comment by Pulpyyyy** [comment]
Hello,
Here is my list, 22 entities with v1.4.0
```
binary_sensor.automower_health_alarm
button.automower_stop
button.automower_auto
sensor.automower_battery_0
button.automower_start
button.automower_sleep
sensor.automower_motor_drive_right
sensor.automower_motor_drive_left
button.automower_shutdown
button.automower_eod
sensor.automower_ext_gpio1
sensor.automower_ext_gpio2
sensor.automower_clock_time
button.automower_man
sensor.automower_motor_blade
sensor.automower_ext_out1
sensor.automower_ext_out2
button.automower_reboot
button.automower_error_reset
sensor.automower_service_call_result
button.automower_home
sensor.automower_weather_service
```

**Comment by geertmeersman** [comment]
I just looked at your screenshot and already see the issue. You did not modify when setting up the integration the MQTT topic.
It seems you have changed it to robonect, where the default is automower.

So I advise you to remove the integration and add it again, specifying robonect as MQTT topic :-) This should solve it

**Comment by Pulpyyyy** [comment]
THANK YOU ! I haven't paid enough attention to the MQTT topic.
I noticed that this is not one of the reconfiguration options.
Also the MQTT monitoring checkbox has a strange behavior : as soon as I unchecked it, it adds 40 new entities
![robonect](https://github.com/geertmeersman/robonect/assets/32004297/01fab11e-4e43-4b75-afe5-3f8ed7abeb98)
Is it normal ?

**Comment by geertmeersman** [comment]
Hi, it had nothing to see with the checkbox, was just a coincidence. In fact it creates the sensors once there is a new topic on the MQTT broker, so just having some patience and it will all have poped up

**Comment by geertmeersman** [comment]
When you uncheck it, it will use the REST sensors instead of the MQTT ones
